### ISSUE TITLE
Container: implement LayoutContainer#getChildren() for Core Components 2.22.x

### ISSUE THREAD

**Issue by Buuhuu** [wcm-io/io.wcm.wcm.core.components#10]
With the Core WCM Components 2.22.x we better separated the concern of list items and container children: https://github.com/adobe/aem-core-wcm-components/pull/2416

This was done to provide a clean fix for https://github.com/adobe/aem-core-wcm-components/pull/2409 that does not require to add a `ListItem#getResource()` which does not make much sense for all ListItems. 

The  [LayoutContainerV1Impl](https://github.com/wcm-io/io.wcm.wcm.core.components/blob/develop/bundles/core/src/main/java/io/wcm/wcm/core/components/impl/models/v1/LayoutContainerV1Impl.java#L54) should implement and delegate `getChildren()`

found while fixing https://github.com/adobe/aem-core-wcm-components/pull/2482

**Comment by stefanseifert** [comment]
thanks for reporting! will look into it.

i'm just waiting for core components 2.22.x to appear in GA AEMaaCS releases to start working on this.
